version: '2'
services:

    etcd1:
        image: quay.io/coreos/etcd:v3.1.7 
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ./certs/:/srv/
        environment:
            ETCD_NAME: node1
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd1:2380
            ETCD_INITIAL_CLUSTER: node3=https://etcd3:2380,node1=https://etcd1:2380,node2=https://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
            ETCD_CERT_FILE: /srv/ca.pem
            ETCD_KEY_FILE: /srv/ca-key.pem
            ETCD_PEER_TRUSTED_CA_FILE: /srv/ca.pem
            ETCD_PEER_CERT_FILE: /srv/etcd1.pem
            ETCD_PEER_KEY_FILE: /srv/etcd1-key.pem
            ETCD_PEER_CLIENT_CERT_AUTH: 1
    etcd2:
        image: quay.io/coreos/etcd:v3.1.7
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ./certs/:/srv/
        environment:
            ETCD_NAME: node2
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd2:2380
            ETCD_INITIAL_CLUSTER: node3=https://etcd3:2380,node1=https://etcd1:2380,node2=https://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: https://etcd2:2379
            ETCD_CERT_FILE: /srv/ca.pem
            ETCD_KEY_FILE: /srv/ca-key.pem
            ETCD_PEER_TRUSTED_CA_FILE: /srv/ca.pem
            ETCD_PEER_CERT_FILE: /srv/etcd2.pem
            ETCD_PEER_KEY_FILE: /srv/etcd2-key.pem
            ETCD_PEER_CLIENT_CERT_AUTH: 1
    etcd3:
        image: quay.io/coreos/etcd:v3.1.7
        restart: always
        ports:
            - 2379
            - 2380
        volumes:
          - ./certs/:/srv/
        environment:
            ETCD_NAME: node3
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: https://etcd3:2380
            ETCD_INITIAL_CLUSTER: node3=https://etcd3:2380,node1=https://etcd1:2380,node2=https://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: https://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: https://etcd3:2379
            ETCD_CERT_FILE: /srv/ca.pem
            ETCD_KEY_FILE: /srv/ca-key.pem
            ETCD_PEER_TRUSTED_CA_FILE: /srv/ca.pem
            ETCD_PEER_CERT_FILE: /srv/etcd3.pem
            ETCD_PEER_KEY_FILE: /srv/etcd3-key.pem
            ETCD_PEER_CLIENT_CERT_AUTH: 1
