version: '2'
services:

    etcd1:
        image: quay.io/coreos/etcd:v3.2.4
        restart: always
        ports:
            - 2379
            - 2380
        environment:
            ETCD_NAME: node1
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
    etcd2:
        image: quay.io/coreos/etcd:v3.2.4
        restart: always
        ports:
            - 2379
            - 2380
        environment:
            ETCD_NAME: node2
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
    etcd3:
        image: quay.io/coreos/etcd:v3.2.4
        restart: always
        ports:
            - 2379
            - 2380
        environment:
            ETCD_NAME: node3
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
    prom:
        image: prom/prometheus:latest
        restart: always
        ports:
            - 9090
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
